id: OnlineTriplet_Hardest
pretrained: null
model:
    name: EfficientNetExtractor
    args:
        version: 0
optimizer:
    name: Adam
    args:
        lr: 0.001
        weight_decay: 0.0001
loss:
    name: OnlineClassificationLoss
    args:
        margin: 1.0
        selector:
            name: HardestNegativeTripletSelector
            args:
                margin: 1.0
metric:
    - name: MeanAP
scheduler:
    name: StepLR
    args:
        step_size: 8
        gamma: 0.1
        last_epoch: -1
dataset:
    train:
        name: AIC2020Track2
        args:
            root: data/AIC20_ReID/image_train
            path: data/list/reid_train_easy.csv
            train: True
        loader:
            name: BalancedBatchDataLoader
            args:
                nclasses: 4
                nsamples: 4
                pin_memory: True
    val:
        name: AIC2020Track2Hard
        args:
            root: data/AIC20_ReID/image_train
            csv_path: data/list/reid_gallery_hard.csv
            json_path: data/list/train_image_metadata.json
            train: False
        loader:
            name: BalancedBatchDataLoader
            args:
                nclasses: 4
                nsamples: 4
                pin_memory: True
trainer:
    nepochs: 10
    val_step: 1
    log_step: 5
