id: OnlineTriplet_Hardest
pretrained: null
model:
    name: EfficientNetExtractor
    args:
        version: 0
optimizer:
    name: Adam
    args:
        lr: 0.0005
        weight_decay: 0.0001
loss:
    name: OnlineTripletLoss
    args:
        margin: 1.0
        selector:
            name: HardestNegativeTripletSelector
            args:
                margin: 1.0
metric:
    - name: MeanAP
      args:
          query:
              name: AIC2020Track2
              args:
                  root: data/AIC20_ReID/image_train
                  path: data/list/reid_direction/reid_query_front_easy.csv
                  train: True
          gallery:
              name: AIC2020Track2
              args:
                  root: data/AIC20_ReID/image_train
                  path: data/list/reid_direction/reid_gallery_front_easy.csv
                  train: True
scheduler:
    name: StepLR
    args:
        step_size: 8
        gamma: 0.1
        last_epoch: -1
dataset:
    train:
        name: AIC2020Track2
        args:
            root: data/AIC20_ReID/image_train
            path: data/list/reid_direction/reid_train_front_easy.csv
            train: True
        loader:
            name: BalancedBatchDataLoader
            args:
                nclasses: 4
                nsamples: 4
                pin_memory: True
    val:
        name: AIC2020Track2
        args:
            root: data/AIC20_ReID/image_train
            path: data/list/reid_direction/reid_gallery_front_easy.csv
            train: True
        loader:
            name: BalancedBatchDataLoader
            args:
                nclasses: 4
                nsamples: 4
                pin_memory: True
trainer:
    nepochs: 10
    val_step: 1
    log_step: 5
